version: '3.8'
services:

  database:
    image: postgres:14
    container_name: books-database
    volumes:
      - pgsql:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=books

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: books-backend
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:1234@database:5432/books
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: books-frontend
    ports:
      - 3000:3000

volumes:
  pgsql:
    external: false